#configs/infer_tracks.yaml

yolo:
  model_path: "artifacts/models/yolov8l.onnx"
  img_size: 640
  conf_thres: 0.35
  iou_thres: 0.50

data:
  input_dir: "/home/bohdan/test_video.mp4"
  save_width: 800
  save_dir: "/home/bohdan/Документи/Samples/Images/boxing_tracker/test"

tracking:
  config_path: "configs/tracking.yaml"
  num_frames_merge: 0
  apperance_embedding_model_path: "artifacts/models/apperance_cnn/apperance_encoder_02_09_mobilenetv3large.keras"

shot_boundary:
  config_path: "configs/shot_boundary.yaml"
